[package]
name        = "flix-regex"
description = "Do not depend on this library."
version     = "0.2.1"
flix        = "0.35.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

